javafx:
  title: JavaFx & SpringBoot
  appicons: /icon/icon.png
  stage:
#    width: 1280
#    height: 720
#    style: DECORATED  # javafx.stage.StageStyle [DECORATED, UNDECORATED, TRANSPARENT, UTILITY, UNIFIED]
#    resizable: false
